[build]
  publish = "."

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200

[[redirects]]
  from = "/api/transcribe"
  to = "/.netlify/functions/transcribe"
  status = 200

[[redirects]]
  from = "/api/score"
  to = "/.netlify/functions/score"
  status = 200

[[redirects]]
  from = "/api/tts"
  to = "/.netlify/functions/tts"
  status = 200
